apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-openshift-monitoring-prometheus-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
