#
# Copyright (c) 2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: che
    component: che-gateway
  name: che-gateway
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: che
      component: che-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: che
        component: che-gateway
    spec:
      serviceAccountName: che-gateway
      containers:
        - name: gateway
          image: {{ .Values.cheGateway.gatewayImage }}
          imagePullPolicy: {{ .Values.cheGateway.imagePullPolicy }}
          volumeMounts:
            - name: static-config
              mountPath: /etc/traefik
            - name: dynamic-config
              mountPath: "/dynamic-config"
        - name: configbump
          image: {{ .Values.cheGateway.configBumpImage }}
          imagePullPolicy: {{ .Values.cheGateway.imagePullPolicy }}
          env:
            - name: CONFIG_BUMP_DIR
              value: "/dynamic-config"
            - name: CONFIG_BUMP_LABELS
              value: {{ .Values.global.singleHostGatewayLabels | quote }}
            - name: CONFIG_BUMP_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: dynamic-config
              mountPath: "/dynamic-config"
      volumes:
        - name: static-config
          configMap:
            name: che-gateway-config
        - name: dynamic-config
          emptyDir: {}
