---
displayName: Java Gradle
description: Java stack with OpenJDK 11, Maven 3.6.3, and Gradle 6.1
tags: ["Java", "OpenJDK", "Maven", "Gradle", "UBI8"]
icon: /images/type-gradle.svg
links:
  v2: https://github.com/crw-samples/gs-validating-form-input/tree/devfilev2
