# This patch sets the default name for the webhooks secret name.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: devworkspace-controller
        env:
        - name: WEBHOOK_SECRET_NAME
          value: devworkspace-webhookserver-tls
