# The prefixed base has to be used separately to add namePrefix to all resources,
# as namePrefix cannot be disabled for specific types, and we need the
# CSV's .metadata.name to be unchanged

bases:
- prefixed
- ../components/csv

patchesStrategicMerge:
- crd_webhooks_patch.yaml
