#### :warning::warning::warning: Functionality of DevWorkspace Che Operator was merged into https://github.com/eclipse-che/che-operator[che-operator] (https://github.com/eclipse-che/che-operator/pull/925[PR#925]). Devworkspace Che Operator is not deployed in Eclipse Che 7.35+ and this repository will not be mainained anymore.

= Che Manager Controller for DevWorkspaces

image:https://github.com/che-incubator/devworkspace-che-operator/workflows/Go%20tests/badge.svg["Go tests"] image:https://codecov.io/gh/che-incubator/devworkspace-che-operator/branch/master/graph/badge.svg?token=37N55V7E6S["Codecov", link="https://codecov.io/gh/che-incubator/devworkspace-che-operator"]


An experimental operator that enhances https://github.com/devfile/devworkspace-operator[Devworkspaces] with Che-specific functionality.

This operator brings support for single-host mode into the devworkspace picture. It is in charge of maintaining and configuring
the HTTP gateway (using Traefik) that serves as the main entrypoint to the devworkspaces and dashboard.

It is also in charge of reconfiguring the gateway to route the traffic to devworkspace endpoints as requested during the workspace startup.

In the future, it is going to be also responsible for authentication of users accessing the Che dashboard and devworkspaces (either in 
the same executable or separately).

== Controllers

There are 2 controllers in this operator. One is in charge of maintaining the state of the Che-specific infrastructure, the other is 
in charge of exposing the devworkspace endpoints.

== Che Cluster Controller

This controller is in charge of the Che-specific infrastructure that is described using the `CheCluster` custom resource defined by
https://github.com/eclipse-che/che-operator[che-operator].

== DevWorkspace Routing Controller

This controller is in charge of exposing the devworkspace endpoints by reconciling the `DevWorkspaceRouting` objects that are themselves managed
by the main devworkspace operator. For this controller to handle the endpoints of a devworkspace, the `DevWorkspace` object describing the
workspace needs to have the `routingClass` property set to `che`.

== Prerequisites

There has to be a running installation of the https://github.com/devfile/devworkspace-operator[devworkspace-operator] running in the cluster.
There also have to be the `CheCluster` custom resource installed in the cluster. Please see https://github.com/eclipse-che/che-operator[che-operator] for the latest version of that.

== Build

To build the code, just run:

```
make
```

There are more things you can do with `make`. To figure out what is available, run:

```
make help
``` 

