// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	exec_info "github.com/eclipse-che/che-machine-exec/exec-info"
	mock "github.com/stretchr/testify/mock"

	model "github.com/eclipse-che/che-machine-exec/api/model"
)

// InfoExecCreator is an autogenerated mock type for the InfoExecCreator type
type InfoExecCreator struct {
	mock.Mock
}

// CreateInfoExec provides a mock function with given fields: command, containerInfo
func (_m *InfoExecCreator) CreateInfoExec(command []string, containerInfo *model.ContainerInfo) exec_info.InfoExec {
	ret := _m.Called(command, containerInfo)

	var r0 exec_info.InfoExec
	if rf, ok := ret.Get(0).(func([]string, *model.ContainerInfo) exec_info.InfoExec); ok {
		r0 = rf(command, containerInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(exec_info.InfoExec)
		}
	}

	return r0
}
