apiVersion: v1
data:
  devworkspace.default_routing_class: basic
  devworkspace.experimental_features_enabled: "false"
  devworkspace.routing.cluster_host_suffix: ""
  devworkspace.sidecar.image_pull_policy: Always
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-configmap
  namespace: devworkspace-controller
