# Adds namespace to all resources.
namespace: ${NAMESPACE}

# Prefix for names of all resources created by this kustomization
namePrefix: devworkspace-controller-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/name: devworkspace-controller
  app.kubernetes.io/part-of: devworkspace-operator

bases:
- ../base

patchesStrategicMerge:
- crd_webhooks_patch.yaml
- manager_service_ca_patch.yaml
- service_cert_patch.yaml
