apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: devworkspace-controller
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-tls-certs
          readOnly: true
      volumes:
      - name: webhook-tls-certs
        secret:
          defaultMode: 420
          secretName: devworkspace-webhooks-tls
