resources:
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# Cluster-edit and view roles for devworkspaces and related resources
- edit_workspaces_cluster_role.yaml
- view_workspaces_cluster_role.yaml
# Clusterroles for metrics auth proxy
- auth_proxy_cluster_role.yaml
- auth_proxy_cluster_role_binding.yaml
- auth_proxy_client_cluster_role.yaml

configurations:
- kustomizeconfig.yaml
